"""Add cloud storage and validation fields to File model

Revision ID: 0a330c46f865
Revises: cae61760dd65
Create Date: 2025-09-04 10:18:54.304045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a330c46f865'
down_revision: Union[str, Sequence[str], None] = 'cae61760dd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_clients_author_id'), table_name='clients')
    op.drop_index(op.f('idx_clients_created_at'), table_name='clients')
    op.add_column('files', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('files', sa.Column('sha256_hash', sa.String(), nullable=True))
    op.add_column('files', sa.Column('storage_provider', sa.String(), nullable=True))
    op.add_column('files', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('files', sa.Column('validation_status', sa.String(), nullable=True))
    op.add_column('files', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('files', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('category', sa.String(), nullable=True))
    op.add_column('files', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('files', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_files_created_at'), table_name='files')
    op.drop_index(op.f('idx_files_report_id'), table_name='files')
    op.drop_index(op.f('idx_files_uploaded_by'), table_name='files')
    op.drop_index(op.f('idx_ocr_results_file_id'), table_name='ocr_results')
    op.drop_index(op.f('idx_properties_report_id'), table_name='properties')
    op.drop_index(op.f('idx_reports_author_id'), table_name='reports')
    op.drop_index(op.f('idx_reports_author_status'), table_name='reports')
    op.drop_index(op.f('idx_reports_created_at'), table_name='reports')
    op.drop_index(op.f('idx_reports_status'), table_name='reports')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('idx_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('idx_reports_author_status'), 'reports', ['author_id', 'status'], unique=False)
    op.create_index(op.f('idx_reports_author_id'), 'reports', ['author_id'], unique=False)
    op.create_index(op.f('idx_properties_report_id'), 'properties', ['report_id'], unique=False)
    op.create_index(op.f('idx_ocr_results_file_id'), 'ocr_results', ['file_id'], unique=False)
    op.create_index(op.f('idx_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_files_report_id'), 'files', ['report_id'], unique=False)
    op.create_index(op.f('idx_files_created_at'), 'files', ['created_at'], unique=False)
    op.drop_column('files', 'uploaded_at')
    op.drop_column('files', 'metadata')
    op.drop_column('files', 'category')
    op.drop_column('files', 'description')
    op.drop_column('files', 'risk_level')
    op.drop_column('files', 'validation_status')
    op.drop_column('files', 'storage_key')
    op.drop_column('files', 'storage_provider')
    op.drop_column('files', 'sha256_hash')
    op.drop_column('files', 'file_url')
    op.create_index(op.f('idx_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('idx_clients_author_id'), 'clients', ['author_id'], unique=False)
    # ### end Alembic commands ###
