"""add_author_id_to_clients

Revision ID: 23f2e2a5e70b
Revises: 7374d4f374e0
Create Date: 2025-08-30 21:55:20.438407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f2e2a5e70b'
down_revision: Union[str, Sequence[str], None] = '7374d4f374e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'clients', 'users', ['author_id'], ['id'])
    op.drop_index(op.f('ix_reports_ref'), table_name='reports')
    op.create_index(op.f('ix_reports_ref'), 'reports', ['ref'], unique=False)
    op.create_index('ix_reports_author_ref', 'reports', ['author_id', 'ref'], unique=True, postgresql_where=sa.text("ref IS NOT NULL AND ref <> ''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_author_ref', table_name='reports', postgresql_where=sa.text("ref IS NOT NULL AND ref <> ''"))
    op.drop_index(op.f('ix_reports_ref'), table_name='reports')
    op.create_index(op.f('ix_reports_ref'), 'reports', ['ref'], unique=True)
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'author_id')
    # ### end Alembic commands ###
